name: Build Docker Image and Upload the Image to Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cups-brother:250930   
      
      - name: Save the Docker image
        run: docker save -o cups-brother.tar cups-brother:250930
