name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cups-brother:$(date +%s)

    - name: Docker Image Artifact Upload
      uses: ishworkh/docker-image-artifact-upload@v2.1.0
      with:
        image: "cups-brother:latest"
        retention_days: 1
            
